
# tap repositories and their packages

tap homebrew/core
brew ack
brew act
brew automake
brew awscli
brew bash
brew bash-completion
brew bat
brew bottom
brew bzip2
brew cmatrix
brew commitizen
brew composer
brew coreutils
brew cowsay
brew deno
brew dnsmasq
brew dolt
brew doltgres
brew duf
brew expat
brew eza
brew fastfetch
brew fd
brew ffmpegthumbnailer
brew fnm
brew fzf
brew gcc
brew gh
brew ghostscript
brew git
brew git-delta
brew git-extras
brew gitui
brew go
brew helix
brew htop
brew httpie
brew ifstat
brew imagemagick
brew jq
brew k6
brew libedit
brew libffi
brew libiconv
brew lnav
brew make
brew mas
brew mcfly
brew mysql-client
brew neonctl
brew neovim
brew nginx
brew ollama
brew openssl@1.1
brew perl
brew pipx
brew poppler
brew postgresql@15
brew pre-commit
brew python-tk@3.13
brew qemu
brew ripgrep
brew rsync
brew rust
brew sevenzip
brew sheldon
brew spice-server
brew starship
brew stow
brew tealdeer
brew temporal
brew tmux
brew tree
brew vim
brew wget
brew xclip
brew yq
brew zellij
brew zig
brew zoxide
brew zsh

tap homebrew/cask
cask 1password
cask 1password-cli
cask balenaetcher
cask beekeeper-studio
cask bruno
cask caffeine
cask calibre
cask canva
cask dbngin
cask discord
cask docker-desktop
cask evkey
cask figma
cask firefox
cask font-cascadia-code
cask font-caskaydia-cove-nerd-font
cask font-fira-code
cask font-fira-code-nerd-font
cask font-fira-mono
cask font-fira-mono-nerd-font
cask font-jetbrains-mono
cask font-jetbrains-mono-nerd-font
cask fork
cask ghostty
cask google-chrome
cask google-drive
cask gpg-suite-no-mail
cask herd
cask linear-linear
cask logi-options+
cask logitech-g-hub
cask messenger
cask microsoft-auto-update
cask microsoft-office
cask microsoft-teams
cask miro
cask nosql-workbench
cask notion
cask numi
cask obs
cask openvpn-connect
cask paintbrush
cask pgadmin4
cask postman
cask rectangle
cask redis-insight
cask rwts-pdfwriter
cask slack
cask spotify
cask steam
cask tableplus
cask via
cask vial
cask visual-studio-code
cask zalo
cask zed
cask zoom

tap homebrew/bundle

tap homebrew/command-not-found

tap homebrew/services

tap atomicjar/tap
cask atomicjar/tap/testcontainers-desktop

tap axiomhq/tap
brew axiomhq/tap/axiom

tap beeftornado/rmtree

tap buo/cask-upgrade

tap common-fate/granted
brew common-fate/granted/granted

tap cowsay-org/cowsay

tap github/gh

tap hashicorp/tap
brew hashicorp/tap/terraform

tap libsql/sqld

tap localstack/tap
brew localstack/tap/localstack-cli

tap nikitabobko/tap
cask nikitabobko/tap/aerospace

tap nikolaeu/numi
brew nikolaeu/numi/numi-cli

tap oven-sh/bun
brew oven-sh/bun/bun

tap rcmdnk/file
brew rcmdnk/file/brew-file

tap sst/tap
brew sst/tap/opencode

tap tursodatabase/tap
brew tursodatabase/tap/turso

# App Store applications
appstore 1569813296 1Password for Safari (8.10.82)
appstore 302584613 Amazon Kindle (7.38.1)
appstore 1091189122 Bear (2.5.1)
appstore 1193539993 Brother iPrint&Scan (12.2.1)
appstore 682658836 GarageBand (10.4.12)
appstore 1555925018 Genki Arcade (1.3.2)
appstore 408981434 iMovie (10.4.3)
appstore 409183694 Keynote (14.4)
appstore 360593530 Notability (14.12.9)
appstore 409203825 Numbers (14.4)
appstore 490179405 Okta Verify (9.46.1)
appstore 409201541 Pages (14.4)
