
# tap repositories and their packages

tap homebrew/core
brew ack
brew act
brew automake
brew awscli
brew bash-completion
brew bat
brew bottom
brew bzip2
brew cmatrix
brew coreutils
brew cowsay
brew direnv
brew duf
brew eksctl
brew expat
brew eza
brew fastfetch
brew fd
brew ffmpegthumbnailer
brew fnm
brew fzf
brew gh
brew ghostscript
brew git
brew git-delta
brew git-extras
brew gitui
brew go
brew helm
brew htop
brew ifstat
brew imagemagick
brew ios-deploy
brew jmeter
brew jpeg
brew jq
brew k6
brew kube-ps1
brew kubectx
brew kubeseal
brew lazygit
brew libedit
brew libffi
brew libiconv
brew libpsl
brew librsvg
brew lld
brew lnav
brew localstack
brew mas
brew maven
brew mcfly
brew neonctl
brew neovim
brew ollama
brew openssl@1.1
brew openvpn
brew oxker
brew perl
brew pidof
brew pipx
brew poppler
brew postgresql@15
brew python-tk@3.14
brew python@3.11
brew qemu
brew rbenv
brew ripgrep
brew rsync
brew rust
brew sevenzip
brew sheldon
brew starship
brew stern
brew stow
brew tealdeer
brew tmux
brew tree
brew vim
brew watch
brew watchman
brew wget
brew xclip
brew yq
brew zellij
brew zlib
brew zoxide
brew zsh

tap homebrew/cask
cask 1password
cask 1password-cli
cask android-studio
cask balenaetcher
cask beekeeper-studio
cask bruno
cask caffeine
cask calibre
cask canva
cask discord
cask docker-desktop
cask evkey
cask firefox
cask font-jetbrains-mono
cask font-jetbrains-mono-nerd-font
cask fork
cask ghostty
cask google-chrome
cask gpg-suite-no-mail
cask jumpcloud-password-manager
cask keymapp
cask logi-options+
cask logitech-g-hub
cask messenger
cask miro
cask notion
cask obs
cask phpstorm
cask postman
cask reactotron
cask rectangle
cask slack
cask spotify
cask stats
cask tableplus
cask via
cask vial
cask visual-studio-code
cask zed
cask zulu@17

tap atomicjar/tap
cask atomicjar/tap/testcontainers-desktop

tap axiomhq/tap
cask axiomhq/tap/axiom

tap beeftornado/rmtree

tap buo/cask-upgrade

tap cargo-lambda/cargo-lambda
brew cargo-lambda/cargo-lambda/cargo-lambda

tap cowsay-org/cowsay

tap derailed/k9s
brew derailed/k9s/k9s

tap facebook/fb
brew facebook/fb/idb-companion

tap felixkratz/formulae
brew felixkratz/formulae/borders
brew felixkratz/formulae/sketchybar

tap fluxcd/tap
brew fluxcd/tap/flux

tap github/gh

tap hashicorp/tap
brew hashicorp/tap/terraform

tap lacework/tap
brew lacework/tap/lacework-cli

tap libsql/sqld

tap localstack/tap
brew localstack/tap/localstack-cli

tap nikitabobko/tap
cask nikitabobko/tap/aerospace

tap nikolaeu/numi
brew nikolaeu/numi/numi-cli

tap oven-sh/bun
brew oven-sh/bun/bun

tap rcmdnk/file
brew rcmdnk/file/brew-file

tap shivammathur/php
brew shivammathur/php/php@8.3

tap sst/tap
brew sst/tap/opencode

tap tursodatabase/tap
brew tursodatabase/tap/turso

tap weaveworks/tap

tap wix/brew
brew wix/brew/applesimutils

# App Store applications
appstore 1569813296 1Password for Safari (8.11.18)
appstore 302584613 Amazon Kindle (7.45.1)
appstore 1091189122 Bear (2.6.5)
appstore 1193539993 Brother iPrint&Scan (14.0)
appstore 682658836 GarageBand (10.4.12)
appstore 1555925018 Genki Arcade (1.3.4)
appstore 408981434 iMovie (10.4.3)
appstore 409183694 Keynote (14.4)
appstore 360593530 Notability (15.1.2)
appstore 409203825 Numbers (14.4)
appstore 409201541 Pages (14.4)
appstore 899247664 TestFlight (4.0.1)
appstore 497799835 Xcode (26.1.1)
