# Hyprland Configuration
# https://wiki.hypr.land/Configuring/

source = ./dms/colors.conf

################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=desc:Xiaomi Corporation Mi Monitor,highrr,auto,auto
monitor = , preferred,auto,auto

###################
### MY PROGRAMS ###
###################

$terminal = ghostty
$fileManager = nautilus

#################
### AUTOSTART ###
#################

exec-once = /usr/lib/pam_kwallet_init
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start hyprland-session.target
exec-once = 1password
exec-once = fcitx5 -d

#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

#####################
### LOOK AND FEEL ###
#####################

general {
    gaps_in = 5
    gaps_out = 5
    border_size = 2

    layout = dwindle
}

decoration {
    rounding = 12

    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 30
        render_power = 5
        offset = 0 5
        color = rgba(00000070)
    }
}

animations {
    enabled = true

    animation = windowsIn, 1, 3, default
    animation = windowsOut, 1, 3, default
    animation = workspaces, 1, 5, default
    animation = windowsMove, 1, 4, default
    animation = fade, 1, 3, default
    animation = border, 1, 3, default
}

dwindle {
    preserve_split = true
}

master {
    mfact = 0.5
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

#############
### INPUT ###
#############

input {
    kb_layout = us
    numlock_by_default = true
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}

gestures {
}

# Example per-device config
# device {
#     name = epic-mouse-v1
#     sensitivity = -0.5
# }

###################
### KEYBINDINGS ###
###################

$mainMod = SUPER

source = ./dms/binds.conf

##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = tile on, match:class ^(org\.wezfurlong\.wezterm)$

windowrule = rounding 12, match:class ^(org\.gnome\.)

windowrule = tile on, match:class ^(gnome-control-center)$
windowrule = tile on, match:class ^(pavucontrol)$
windowrule = tile on, match:class ^(nm-connection-editor)$

windowrule = float on, match:class ^(gnome-calculator)$
windowrule = float on, match:class ^(galculator)$
windowrule = float on, match:class ^(blueman-manager)$
windowrule = float on, match:class ^(org\.gnome\.Nautilus)$
windowrule = float on, match:class ^(xdg-desktop-portal)$

windowrule = no_initial_focus on, match:class ^(steam)$, match:title ^(notificationtoasts)
windowrule = pin on, match:class ^(steam)$, match:title ^(notificationtoasts)

windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(zoom)$

layerrule = no_anim on, match:namespace ^(quickshell)$
layerrule = no_anim on, match:namespace ^dms:.*

source = ./dms/outputs.conf
source = ./dms/layout.conf
source = ./dms/cursor.conf
