shell = "zsh"

[plugins]

[plugins.base16]
github = "chriskempson/base16-shell"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.wezterm]
github = "wez/wezterm"
use = ["assets/shell-integration/wezterm.sh"]
